baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
contentDir = "content"
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
contentDir = "content"
