name: Force Register Hugo Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test-register:
    runs-on: ubuntu-latest
    steps:
      - run: echo "[OK] Workflow registration test triggered successfully"
