name: Hugo Build → Store to gh-pages (정석)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  build-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.150.1"
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install deps
        run: npm ci || npm install

      - name: Build (main → public)
        run: hugo --gc --minify --cleanDestinationDir

      - name: Store artifact to gh-pages (deploy-only branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          commit_message: "deploy: public → gh-pages (build from ${{ github.sha }})"

      - name: Deploy to Cloudflare Pages (CDN)
        run: npx wrangler pages deploy public --project-name="${{ secrets.CF_PROJECT_NAME }}" --branch=production
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN:  ${{ secrets.CF_API_TOKEN }}

      - name: Sync Lovable Dashboard
        run: echo "[OK] 러버블 KPI 대시보드 병합 및 정석 빌드 완료"
