name: Hugo Build and Deploy (정석 안정판)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

# ✅ 병렬 배포 자동 취소
concurrency:
  group: github-pages
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Safety delay before build
        run: sleep 10

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.150.1"
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install deps
        run: npm ci || npm install

      - name: Build Hugo
        run: hugo --gc --minify --cleanDestinationDir

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages

