name: Test GSC Secret
on:
  workflow_dispatch:

jobs:
  verify-gsc:
    runs-on: ubuntu-latest
    steps:
      - name: Validate GSC Secret JSON
        run: |
          echo "$GSC_SECRET" > gsc.json
          python3 -c "import json; json.load(open('gsc.json'))"
          echo "[OK] GSC_SECRET JSON structure valid"
        env:
          GSC_SECRET: ${{ secrets.GSC_SECRET }}
